[build]
target = "src/kernel/arch/x86_64/cfg/x86_64.json"
rustflags = ["-Cforce-frame-pointers=yes"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(all())']
runner = "./start.sh"
